apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-user: cG9zdGdyZXM=      # "postgres" (base64 encoded)
  postgres-password: MTIzNDU=       # "12345" (base64 encoded)
  postgres-db: c2hvd3RpbWVz         # "showtimes" (base64 encoded)
